#!/usr/bin/env bash
# Configure Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Replace existing entry for localhost with new one
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts

# Add entry for facebook.com
echo "8.8.8.8 facebook.com" >> /etc/hosts