#!/usr/bin/env bash
# Configure Ubuntu server to resolve localhost to 127.0.0.2 and facebook.com to 8.8.8.8

# Add entries to /etc/hosts file
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts